package com.project.assignment2

// A simple data class representing one location record from the database.
// This model is used to hold data for each location retrieved, inserted, or updated.

data class LocationModel(
    val id: Long,          // Unique ID for the location (auto-generated by SQLite)
    val address: String,   // Name of the place (e.g., "Oshawa", "Toronto", etc.)
    val latitude: Double,  // Latitude coordinate of the location
    val longitude: Double  // Longitude coordinate of the location
)